version: "2"
services:
  nginx:
    restart: always
    build: ./docker/nginx/
    image: quay.io/sanbi-sa/baobab-nginx:1.15
    container_name: baobab_nginx
    ports:
      - "80:80"
    links:
      - baobab_lims
  baobab_lims:
    restart: always
    build: ./docker/
    image: quay.io/sanbi-sa/baobab-lims:1.4.0
    container_name: baobab_lims
    ports:
      - "8080:8080"
